import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import styles from '@/app/page.module.css';

export const metadata: Metadata = {
  metadataBase: new URL('https://portfoliosakthi.vercel.app'),
  title: {
    default: 'Sakthivelpandian P. | AI-Focused Software Developer & GIS Operator',
    template: '%s | Sakthivelpandian P.',
  },
  description:
    'Official portfolio of Sakthivelpandian P. - AI-focused software developer and GIS Operator at SSB. Expert in React, Next.js, Gemini API, Node.js, and GIS mapping.',
  keywords: [
    "Sakthivelpandian",
    "Sakthivelpandian P",
    "Sakthivelpandian portfolio",
    "Sakthivelpandian developer",
    "Sakthivelpandian software engineer",
    "Sakthivelpandian GIS",
    "Sakthivelpandian SSB",
    "Sakthivelpandian Tamilnadu",
    "Sakthivelpandian Theni",
    "Sakthivelpandian computer science",
    "imsakthidev",
    "imsakthidev github",
    "Sakthivelpandian P portfolio",
    "Sakthivelpandian P developer",
    "Sakthivelpandian P engineer",
    "Sakthivelpandian P resume",
    "Sakthivelpandian contact",
    "Sakthivelpandian email",
    "Sakthivelpandian phone",
    "Sakthivelpandian website",
    "Sakthivelpandian Vercel",
    "Sakthivelpandian GitHub",
    "Sakthivelpandian full stack",
    "Sakthivelpandian AI",
    "Sakthi developer",
    "Sakthi software engineer",
    "Sakthi GIS operator",
    "Sakthi SSB",
    "Sakthi portfolio",
    "Sakthi Theni",
    "Sakthi Tamilnadu",
    "Sakthi full stack",
    "Sakthivelpandian official website",
    "Sakthivelpandian biography",
    "Sakthivelpandian projects",
    "Sakthivelpandian skills",
    "Sakthivelpandian education",
    "Sakthivelpandian experience",
    "Sakthivelpandian Nanpara",
    "Sakthivelpandian Bahraich",
    "Sakthivelpandian bio",
    "Sakthivelpandian profile",
    "Sakthivelpandian credentials",
    "Sakthivelpandian achievements",
    "Sakthivelpandian mobile 9585992141",
    "Sakthivelpandian mail imsakthidev",
    "Sakthivelpandian web developer",
    "AI-focused software developer",
    "AI developer",
    "AI software engineer",
    "AI full stack developer",
    "Gemini API developer",
    "Vercel AI SDK developer",
    "Prompt engineer",
    "Generative AI developer",
    "Conversational AI developer",
    "LLM application developer",
    "AI chatbot developer",
    "Full stack AI engineer",
    "AI integration specialist",
    "AI SaaS developer",
    "Google Gemini developer",
    "Gemini AI SDK",
    "AI app developer",
    "AI web developer",
    "AI application engineer",
    "Artificial intelligence developer",
    "Generative AI specialist",
    "AI solutions architect",
    "Custom AI chatbot developer",
    "Streaming AI response developer",
    "AI frontend developer",
    "AI backend developer",
    "AI automation developer",
    "AI product developer",
    "AI tools specialist",
    "Prompt engineering specialist",
    "AI workflow developer",
    "AI full stack specialist",
    "Generative AI developer India",
    "AI chatbot specialist Tamilnadu",
    "AI software consultant",
    "Gemini API integration developer",
    "Vercel AI SDK consultant",
    "Streaming response chatbot developer",
    "React developer",
    "Next.js developer",
    "Nextjs developer",
    "TypeScript developer",
    "JavaScript developer",
    "HTML5 CSS3 developer",
    "Tailwind CSS developer",
    "UI UX engineer",
    "Frontend engineer",
    "React.js specialist",
    "Web application developer",
    "Responsive web design",
    "Next.js 16 developer",
    "Turbopack developer",
    "Client side rendering specialist",
    "Server side rendering specialist",
    "Single page application developer",
    "Glassmorphism UI design",
    "Modern web developer",
    "React component developer",
    "TypeScript full stack developer",
    "Frontend UI developer",
    "Modern CSS developer",
    "Flexbox Grid specialist",
    "Web developer Tamilnadu",
    "Web developer Theni",
    "React developer India",
    "Nextjs developer India",
    "Web design specialist",
    "Custom web application developer",
    "Progressive web app developer",
    "Frontend performance optimization",
    "React Nextjs developer Tamilnadu",
    "Tailwind CSS UI specialist",
    "Responsive web developer South India",
    "Node.js developer",
    "Express.js developer",
    "MongoDB developer",
    "Firebase developer",
    "Firebase Authentication",
    "Firestore developer",
    "REST API developer",
    "Full stack Node developer",
    "Backend engineer",
    "Serverless developer",
    "Cloud developer",
    "SQLite developer",
    "Electron desktop app developer",
    "NoSQL database specialist",
    "JSON REST API developer",
    "Nodejs backend developer",
    "Full stack web developer",
    "Backend API architect",
    "Database administrator MongoDB",
    "Firebase hosting specialist",
    "Electron JS developer",
    "Cross platform desktop developer",
    "Windows macOS app developer",
    "Offline desktop app developer",
    "Local database developer",
    "Full stack developer India",
    "Software architect",
    "Cloud backend engineer",
    "Nodejs MongoDB developer India",
    "Firebase full stack developer",
    "SQLite desktop application developer",
    "GIS Operator",
    "GIS Specialist",
    "GIS Analyst",
    "QGIS operator",
    "Google Earth GIS",
    "Geospatial data analyst",
    "Digital map editor",
    "GPS data specialist",
    "Spatial data visualization",
    "Operational mapping specialist",
    "SSB GIS operator",
    "Geospatial developer",
    "GIS mapping specialist",
    "QGIS map editor",
    "Operational GIS specialist",
    "Geospatial intelligence analyst",
    "Geographic information system operator",
    "Digital mapping specialist",
    "GIS records manager",
    "Geospatial data visualization",
    "GPS mapping operator",
    "Commandant appreciation letter SSB",
    "SSB Nanpara GIS",
    "SSB 59 Bn GIS",
    "Central Armed Police Forces GIS",
    "Intelligence GIS mapping",
    "Seizure operation GIS data",
    "GIS operational reports",
    "Sashastra Seema Bal GIS operator",
    "Ministry of Home Affairs GIS",
    "QGIS Google Earth specialist",
    "Software developer Theni",
    "Developer Tamilnadu",
    "Full stack developer Chennai",
    "Developer Coimbatore",
    "React developer Tamilnadu",
    "AI engineer South India",
    "Developer Nanpara",
    "Developer Bahraich",
    "Tamilnadu College of Engineering alumni",
    "Computer science engineer Tamilnadu",
    "Software engineer Theni",
    "Software developer Tamilnadu",
    "Web developer Theni Tamilnadu",
    "Full stack engineer Theni",
    "GIS operator Uttar Pradesh",
    "GIS operator Bahraich",
    "GIS operator Nanpara",
    "Software engineer Coimbatore",
    "Computer science graduate Coimbatore",
    "Best software developer Theni",
    "Top AI developer Tamilnadu",
    "Freelance developer Theni",
    "Web developer Coimbatore",
    "Sakthi Speaks Digital",
    "Sakthi Speaks Digital platform",
    "Digital Growth Consultant chatbot",
    "Smart Moi",
    "Smart Moi desktop application",
    "Tamil Moi collection software",
    "Smart Moi app",
    "Smart Moi Windows macOS",
    "Electron SQLite Smart Moi",
    "Moi collection record software",
    "Vercel deployed portfolio",
    "portfoliosakthi.vercel.app",
    "Sakthivelpandian portfolio website",
    "Tamil Moi management app",
    "Moi registry software",
    "Smart Moi local database",
    "Custom chatbot platform",
    "Tamil Moi collection record app",
    "Offline Tamil Moi app",
    "Sakthi Speaks Digital AI chatbot",
    "Computer Science Teacher",
    "PG Assistant Computer Science",
    "Hayagreeva Vidhyalaya teacher",
    "Python teacher Theni",
    "C++ teacher Class 11 12",
    "SQL instructor",
    "Algorithms instructor",
    "Computer science faculty",
    "School computer teacher",
    "Programming instructor Tamilnadu",
    "Computer science engineering graduate",
    "BE Computer Science Tamilnadu",
    "Coimbatore engineering graduate",
    "Computer science teacher Tamilnadu",
    "High school programming teacher",
    "Python SQL teacher",
    "Available for hire software developer",
    "Hire AI developer",
    "Hire full stack developer",
    "Freelance AI engineer",
    "Remote software developer India",
    "Contract full stack developer",
    "Full stack consultant",
    "Digital consultant",
    "Software operational specialist",
    "Technical operator SSB",
    "Constable GIS SSB",
    "Sashastra Seema Bal GIS",
    "Devotion to duty award SSB",
    "Computer science professional",
    "Tech stack specialist",
    "Modern web architect",
    "Software engineer portfolio 2026",
    "Full stack developer portfolio 2026",
    "AI software developer portfolio",
    "Sakthivelpandian P AI software developer",
    "Sakthivelpandian P GIS operator",
    "Sakthivelpandian P SSB Constable",
    "Sakthivelpandian P React Nextjs",
    "Sakthivelpandian P Nodejs Firebase",
    "Sakthivelpandian P QGIS Google Earth",
    "Sakthivelpandian P Electron SQLite",
    "Sakthivelpandian P Smart Moi",
    "Sakthivelpandian P Sakthi Speaks Digital",
    "Sakthivelpandian P Theni Tamilnadu",
    "Sakthivelpandian P Coimbatore engineering",
    "Sakthivelpandian P Hayagreeva Vidhyalaya",
    "Sakthivelpandian P 9585992141",
    "Sakthivelpandian P imsakthidev@gmail.com",
    "Sakthivelpandian P GitHub profile",
    "Sakthivelpandian P Vercel app",
    "Sakthivelpandian P web app developer",
    "Sakthivelpandian P full stack engineer",
    "Sakthivelpandian P AI chatbot engineer",
    "Sakthivelpandian P prompt engineer",
    "Sakthivelpandian P Gemini API",
    "Sakthivelpandian P Vercel AI SDK",
    "Sakthivelpandian P Nextjs 16",
    "Sakthivelpandian P Turbopack",
    "Sakthivelpandian P Tailwind CSS",
    "Sakthivelpandian P TypeScript",
    "Sakthivelpandian P JavaScript",
    "Sakthivelpandian P MongoDB",
    "Sakthivelpandian P Expressjs",
    "Sakthivelpandian P REST API",
    "Sakthivelpandian P GIS mapping",
    "Sakthivelpandian P digital map editing",
    "Sakthivelpandian P operational mapping",
    "Sakthivelpandian P GPS data",
    "Sakthivelpandian P SSB seizure operation",
    "Sakthivelpandian P Commandant letter",
    "Sakthivelpandian P computer science teacher",
    "Sakthivelpandian P Python C++ SQL",
    "Sakthivelpandian P Class 11 12 teacher",
    "Sakthivelpandian P Tamilnadu College of Engineering",
    "Sakthivelpandian P BE CS 2017",
    "Sakthivelpandian P Available for Hire"
],
  authors: [{ name: 'Sakthivelpandian P', url: 'https://portfoliosakthi.vercel.app' }],
  creator: 'Sakthivelpandian P',
  publisher: 'Sakthivelpandian P',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://portfoliosakthi.vercel.app',
    siteName: 'Sakthivelpandian P Portfolio',
    title: 'Sakthivelpandian P. | AI-Focused Software Developer & GIS Operator',
    description:
      'Official portfolio of Sakthivelpandian P. - AI-focused software developer and GIS Operator at SSB.',
    images: [
      {
        url: '/photo.jpg',
        width: 400,
        height: 400,
        alt: 'Sakthivelpandian P',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Sakthivelpandian P. | AI-Focused Software Developer',
    description:
      'Official portfolio of Sakthivelpandian P. - AI-focused software developer and GIS Operator at SSB.',
    images: ['/photo.jpg'],
  },
  alternates: {
    canonical: 'https://portfoliosakthi.vercel.app',
  },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Sakthivelpandian P',
  alternateName: 'Sakthi',
  url: 'https://portfoliosakthi.vercel.app',
  image: 'https://portfoliosakthi.vercel.app/photo.jpg',
  jobTitle: 'AI-Focused Software Developer & GIS Operator',
  worksFor: {
    '@type': 'Organization',
    name: 'Sashastra Seema Bal (SSB)',
  },
  sameAs: [
    'https://github.com/imsakthidev',
    'mailto:imsakthidev@gmail.com',
  ],
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Theni',
    addressRegion: 'Tamilnadu',
    addressCountry: 'India',
  },
  knowsAbout: [
    "Sakthivelpandian",
    "Sakthivelpandian P",
    "Sakthivelpandian portfolio",
    "Sakthivelpandian developer",
    "Sakthivelpandian software engineer",
    "Sakthivelpandian GIS",
    "Sakthivelpandian SSB",
    "Sakthivelpandian Tamilnadu",
    "Sakthivelpandian Theni",
    "Sakthivelpandian computer science",
    "imsakthidev",
    "imsakthidev github",
    "Sakthivelpandian P portfolio",
    "Sakthivelpandian P developer",
    "Sakthivelpandian P engineer",
    "Sakthivelpandian P resume",
    "Sakthivelpandian contact",
    "Sakthivelpandian email",
    "Sakthivelpandian phone",
    "Sakthivelpandian website",
    "Sakthivelpandian Vercel",
    "Sakthivelpandian GitHub",
    "Sakthivelpandian full stack",
    "Sakthivelpandian AI",
    "Sakthi developer",
    "Sakthi software engineer",
    "Sakthi GIS operator",
    "Sakthi SSB",
    "Sakthi portfolio",
    "Sakthi Theni",
    "Sakthi Tamilnadu",
    "Sakthi full stack",
    "Sakthivelpandian official website",
    "Sakthivelpandian biography",
    "Sakthivelpandian projects",
    "Sakthivelpandian skills",
    "Sakthivelpandian education",
    "Sakthivelpandian experience",
    "Sakthivelpandian Nanpara",
    "Sakthivelpandian Bahraich",
    "Sakthivelpandian bio",
    "Sakthivelpandian profile",
    "Sakthivelpandian credentials",
    "Sakthivelpandian achievements",
    "Sakthivelpandian mobile 9585992141",
    "Sakthivelpandian mail imsakthidev",
    "Sakthivelpandian web developer",
    "AI-focused software developer",
    "AI developer",
    "AI software engineer"
  ],
  verification: {
    google: 'Al0th2ZA8M6PKZHrUDc8cDJFbbR6lrI0wxS3iy0DP4c',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>
        <Navbar />
        <main style={{ minHeight: '100vh', paddingTop: '80px' }}>
          {children}
        </main>
        {/* Shared Footer */}
        <footer className={styles.footer}>
          <div className="container">
            <p>© {new Date().getFullYear()} Sakthivelpandian P. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
