import re

raw_keywords = [
    # 1. Name & Identity Variations (50)
    "Sakthivelpandian",
    "Sakthivelpandian P",
    "Sakthivelpandian portfolio",
    "Sakthivelpandian developer",
    "Sakthivelpandian software engineer",
    "Sakthivelpandian GIS",
    "Sakthivelpandian SSB",
    "Sakthivelpandian Tamilnadu",
    "Sakthivelpandian Theni",
    "Sakthivelpandian computer science",
    "imsakthidev",
    "imsakthidev github",
    "Sakthivelpandian P engineer",
    "Sakthivelpandian P resume",
    "Sakthivelpandian contact",
    "Sakthivelpandian email",
    "Sakthivelpandian phone",
    "Sakthivelpandian website",
    "Sakthivelpandian Vercel",
    "Sakthivelpandian GitHub",
    "Sakthivelpandian full stack",
    "Sakthivelpandian AI",
    "Sakthi developer",
    "Sakthi software engineer",
    "Sakthi GIS operator",
    "Sakthi SSB",
    "Sakthi portfolio",
    "Sakthi Theni",
    "Sakthi Tamilnadu",
    "Sakthi full stack",
    "Sakthivelpandian official website",
    "Sakthivelpandian biography",
    "Sakthivelpandian projects",
    "Sakthivelpandian skills",
    "Sakthivelpandian education",
    "Sakthivelpandian experience",
    "Sakthivelpandian Nanpara",
    "Sakthivelpandian Bahraich",
    "Sakthivelpandian bio",
    "Sakthivelpandian profile",
    "Sakthivelpandian credentials",
    "Sakthivelpandian achievements",
    "Sakthivelpandian mobile 9585992141",
    "Sakthivelpandian mail imsakthidev",
    "Sakthivelpandian web developer",
    "AI-focused software developer",
    "AI developer",
    "AI software engineer",
    "Sakthivelpandian P portfolio website",
    "Sakthivelpandian P official portfolio",

    # 2. AI & Machine Learning Specialties (50)
    "AI full stack developer",
    "Gemini API developer",
    "Vercel AI SDK developer",
    "Prompt engineer",
    "Generative AI developer",
    "Conversational AI developer",
    "LLM application developer",
    "AI chatbot developer",
    "Full stack AI engineer",
    "AI integration specialist",
    "AI SaaS developer",
    "Google Gemini developer",
    "Gemini AI SDK",
    "AI app developer",
    "AI web developer",
    "AI application engineer",
    "Artificial intelligence developer",
    "Generative AI specialist",
    "AI solutions architect",
    "Custom AI chatbot developer",
    "Streaming AI response developer",
    "AI frontend developer",
    "AI backend developer",
    "AI automation developer",
    "AI product developer",
    "AI tools specialist",
    "Prompt engineering specialist",
    "AI workflow developer",
    "AI full stack specialist",
    "Generative AI developer India",
    "AI chatbot specialist Tamilnadu",
    "AI software consultant",
    "Gemini API integration developer",
    "Vercel AI SDK consultant",
    "Streaming response chatbot developer",
    "Next.js AI developer",
    "React AI developer",
    "AI prompt optimizer",
    "Custom LLM interface developer",
    "AI web app engineer",
    "LLM frontend specialist",
    "AI agent developer",
    "Autonomous AI software engineer",
    "AI model API integrator",
    "RAG application developer",
    "AI assistant developer",
    "Nextjs 16 AI engineer",
    "Tailwind AI UI developer",
    "AI portfolio engineer",
    "Generative AI consultant India",

    # 3. Frontend & Modern Web Tech (50)
    "React developer",
    "Next.js developer",
    "Nextjs 16 developer",
    "TypeScript developer",
    "Tailwind CSS developer",
    "Frontend engineer",
    "JavaScript developer",
    "HTML5 CSS3 developer",
    "Responsive web design",
    "Modern web developer",
    "Single page application developer",
    "Server side rendering Nextjs",
    "Static site generation Nextjs",
    "Turbopack developer",
    "UI UX developer",
    "Frontend web architect",
    "Clean code developer",
    "Component based architecture",
    "Web performance optimization",
    "Core web vitals optimization",
    "Accessibility web developer",
    "Mobile responsive developer",
    "Cross browser developer",
    "Frontend UI specialist",
    "Modern JavaScript engineer",
    "ES6+ developer",
    "React hooks specialist",
    "Custom React components",
    "Tailwind UI designer",
    "Next.js App Router developer",
    "Dynamic routing Nextjs",
    "SEO optimized frontend",
    "React web app developer",
    "Web layout engineer",
    "CSS Flexbox grid developer",
    "Client side rendering React",
    "Next.js page speed specialist",
    "Modern web UI engineer",
    "Frontend state management",
    "React performance developer",
    "Nextjs static export",
    "Progressive web application engineer",
    "Web standard compliant developer",
    "Modern frontend architect",
    "High speed web developer",
    "Next.js Turbopack specialist",
    "Tailwind CSS styling expert",
    "Clean JSX developer",
    "Responsive UI developer",
    "React TypeScript engineer",

    # 4. Backend & Full Stack Development (50)
    "Node.js developer",
    "Express.js developer",
    "MongoDB developer",
    "Firebase developer",
    "Firebase Authentication",
    "Firestore developer",
    "REST API developer",
    "Full stack Node developer",
    "Backend engineer",
    "Serverless developer",
    "Cloud developer",
    "SQLite developer",
    "Electron desktop app developer",
    "NoSQL database specialist",
    "JSON REST API developer",
    "Nodejs backend developer",
    "Full stack web developer",
    "Backend API architect",
    "Database administrator MongoDB",
    "Firebase hosting specialist",
    "Electron JS developer",
    "Cross platform desktop developer",
    "Windows macOS app developer",
    "Offline desktop app developer",
    "Local database developer",
    "Full stack developer India",
    "Software architect",
    "Cloud backend engineer",
    "Nodejs MongoDB developer India",
    "Firebase full stack developer",
    "SQLite desktop application developer",
    "Node.js REST API architect",
    "Express server developer",
    "Async JavaScript developer",
    "Backend security developer",
    "Database schema designer",
    "NoSQL query optimization",
    "Firebase rules security",
    "Full stack JavaScript developer",
    "Server side Node developer",
    "Microservices backend developer",
    "Custom API developer",
    "Cloud function developer",
    "Desktop GUI developer Electron",
    "Desktop software engineer",
    "Local data storage SQLite",
    "Full stack software craftsman",
    "Serverless API developer",
    "Nodejs microservices engineer",
    "Backend system developer",

    # 5. GIS & Geospatial Expertise (50)
    "GIS Operator",
    "GIS Specialist",
    "GIS Analyst",
    "QGIS operator",
    "Google Earth GIS",
    "Geospatial data analyst",
    "Digital map editor",
    "GPS data specialist",
    "Spatial data visualization",
    "Operational mapping specialist",
    "SSB GIS operator",
    "Geospatial developer",
    "GIS mapping specialist",
    "QGIS map editor",
    "Operational GIS specialist",
    "Geospatial intelligence analyst",
    "Geographic information system operator",
    "Digital mapping specialist",
    "GIS records manager",
    "GPS mapping operator",
    "Commandant appreciation letter SSB",
    "SSB Nanpara GIS",
    "SSB 59 Bn GIS",
    "Central Armed Police Forces GIS",
    "Intelligence GIS mapping",
    "Seizure operation GIS data",
    "GIS operational reports",
    "Sashastra Seema Bal GIS operator",
    "Ministry of Home Affairs GIS",
    "QGIS Google Earth specialist",
    "Spatial analysis operator",
    "Topographical map analyst",
    "GIS data processing",
    "GIS digitizer",
    "Vector map editing",
    "Raster data analyst",
    "GPS track analyst",
    "GIS border security operator",
    "Tactical GIS mapping",
    "Border surveillance GIS",
    "Spatial intelligence specialist",
    "GIS mapping consultant",
    "Map digitizing specialist",
    "QGIS plugin user",
    "Spatial database operator",
    "Geographic data scientist",
    "Cartography specialist",
    "Geospatial map designer",
    "GIS operational intelligence",
    "Spatial data management",

    # 6. Location-Specific Keywords (50)
    "Software developer Theni",
    "Developer Tamilnadu",
    "Full stack developer Chennai",
    "Developer Coimbatore",
    "React developer Tamilnadu",
    "AI engineer South India",
    "Developer Nanpara",
    "Developer Bahraich",
    "Tamilnadu College of Engineering alumni",
    "Computer science engineer Tamilnadu",
    "Software engineer Theni",
    "Software developer Tamilnadu",
    "Web developer Theni Tamilnadu",
    "Full stack engineer Theni",
    "GIS operator Uttar Pradesh",
    "GIS operator Bahraich",
    "GIS operator Nanpara",
    "Software engineer Coimbatore",
    "Computer science graduate Coimbatore",
    "Best software developer Theni",
    "Top AI developer Tamilnadu",
    "Freelance developer Theni",
    "Web developer Coimbatore",
    "Software developer Madurai",
    "Software engineer Dindigul",
    "Web developer Tiruchirappalli",
    "Developer Salem",
    "Developer Erode",
    "Software developer Tirupur",
    "Full stack developer South India",
    "Top React developer Tamilnadu",
    "Web engineer Theni district",
    "Software developer Periyakulam",
    "Software developer Bodinayakanur",
    "Software engineer Cumbum",
    "Software developer Uttar Pradesh",
    "Technical operator Nanpara Bahraich",
    "Remote developer Tamilnadu",
    "India software engineer",
    "Indian full stack developer",
    "Web developer Tamilnadu state",
    "South Indian software engineer",
    "Software developer Chennai Tamilnadu",
    "Developer Coimbatore India",
    "Freelance web developer Tamilnadu",
    "Software engineering Tamilnadu",
    "Top web developer Theni",
    "Best full stack developer Theni",
    "Leading developer Tamilnadu",
    "Software architect South India",

    # 7. Projects & Digital Solutions (50)
    "Sakthi Speaks Digital",
    "Sakthi Speaks Digital platform",
    "Digital Growth Consultant chatbot",
    "Smart Moi",
    "Smart Moi desktop application",
    "Tamil Moi collection software",
    "Smart Moi app",
    "Smart Moi Windows macOS",
    "Electron SQLite Smart Moi",
    "Moi collection record software",
    "Vercel deployed portfolio",
    "portfoliosakthi.vercel.app",
    "Sakthivelpandian portfolio website",
    "Tamil Moi management app",
    "Moi registry software",
    "Smart Moi local database",
    "Custom chatbot platform",
    "Tamil Moi collection record app",
    "Offline Tamil Moi app",
    "Sakthi Speaks Digital AI chatbot",
    "Smart Moi collection registry",
    "Traditional Tamil Moi digital app",
    "Marriage Moi record software",
    "Functions Moi tracking app",
    "Desktop Moi counter app",
    "Local SQLite Moi database",
    "Electron desktop Moi app",
    "Digital growth AI consultant",
    "Business AI chatbot platform",
    "Custom AI assistant Sakthi Speaks",
    "Portfoliosakthi web app",
    "Nextjs portfolio project",
    "Vercel hosted Nextjs portfolio",
    "React Nextjs showcase",
    "AI developer portfolio website",
    "Full stack project showcase",
    "Responsive portfolio site",
    "Custom portfolio Sakthivelpandian",
    "Digital map showcase GIS",
    "SSB appreciation showcase",
    "Software projects Sakthivelpandian",
    "Sakthi Speaks platform",
    "Smart Moi software download",
    "Tamil function record app",
    "Event gift tracker software",
    "Traditional function record app",
    "SQLite offline desktop tool",
    "Cross platform desktop tool",
    "Next.js 16 Vercel deployment",
    "Smart Moi Tamil application",

    # 8. Education & Teaching Keywords (50)
    "Computer Science Teacher",
    "PG Assistant Computer Science",
    "Hayagreeva Vidhyalaya teacher",
    "Python teacher Theni",
    "C++ teacher Class 11 12",
    "SQL instructor",
    "Algorithms instructor",
    "Computer science faculty",
    "School computer teacher",
    "Programming instructor Tamilnadu",
    "Computer science engineering graduate",
    "BE Computer Science Tamilnadu",
    "Coimbatore engineering graduate",
    "Computer science teacher Tamilnadu",
    "High school programming teacher",
    "Python SQL teacher",
    "Computer science pedagogy",
    "Secondary school computer teacher",
    "CBSE computer science teacher",
    "Higher secondary CS teacher",
    "Programming fundamentals teacher",
    "Data structures instructor",
    "Object oriented programming teacher",
    "C++ programming instructor",
    "Python coding teacher",
    "School coding mentor",
    "Computer science curriculum teacher",
    "High school IT teacher",
    "Computer science lab instructor",
    "Tech educator Tamilnadu",
    "BE CS 2017 graduate",
    "Tamilnadu engineering alumnus",
    "Computer science degree holder",
    "Software engineering educator",
    "Coding tutor Theni",
    "Python tutor Tamilnadu",
    "Computer teacher Hayagreeva",
    "Senior computer teacher",
    "Class 11 CS teacher",
    "Class 12 CS teacher",
    "Computer science exam trainer",
    "Board exam CS instructor",
    "School technology teacher",
    "Computer concepts instructor",
    "Database concepts teacher",
    "SQL queries instructor",
    "High school software mentor",
    "Academic programming instructor",
    "Educator Sakthivelpandian",
    "Teaching experience computer science",

    # 9. Career, Hiring & Freelance (50)
    "Available for hire software developer",
    "Hire AI developer",
    "Hire full stack developer",
    "Freelance AI engineer",
    "Remote software developer India",
    "Contract full stack developer",
    "Full stack consultant",
    "Digital consultant",
    "Software operational specialist",
    "Technical operator SSB",
    "Constable GIS SSB",
    "Sashastra Seema Bal GIS",
    "Devotion to duty award SSB",
    "Computer science professional",
    "Tech stack specialist",
    "Modern web architect",
    "Software engineer portfolio 2026",
    "Full stack developer portfolio 2026",
    "AI software developer portfolio",
    "Hire React developer India",
    "Hire Next.js developer Tamilnadu",
    "Hire GIS specialist India",
    "Freelance web developer India",
    "Remote full stack engineer",
    "Contract web developer Tamilnadu",
    "Hire Node.js backend developer",
    "Freelance GIS map editor",
    "Hire prompt engineer India",
    "Software development freelancer",
    "Full stack contractor India",
    "Web development consultant",
    "IT consultant Tamilnadu",
    "Software engineer for hire",
    "Remote AI developer for hire",
    "Dedicated full stack developer",
    "Portfolio website 2026",
    "Top rated software engineer",
    "Senior software developer portfolio",
    "Experienced web developer",
    "Professional GIS operator",
    "Security force GIS operator",
    "Government service GIS operator",
    "Ex SSB GIS specialist",
    "Commended technical operator",
    "Award winning GIS operator",
    "High performance web engineer",
    "Results driven full stack developer",
    "Dedicated AI developer",
    "Expert web architect India",
    "Professional software consultant",

    # 10. Targeted long-tail search queries (50)
    "Sakthivelpandian P AI software developer",
    "Sakthivelpandian P GIS operator",
    "Sakthivelpandian P SSB Constable",
    "Sakthivelpandian P React Nextjs",
    "Sakthivelpandian P Nodejs Firebase",
    "Sakthivelpandian P QGIS Google Earth",
    "Sakthivelpandian P Electron SQLite",
    "Sakthivelpandian P Smart Moi",
    "Sakthivelpandian P Sakthi Speaks Digital",
    "Sakthivelpandian P Theni Tamilnadu",
    "Sakthivelpandian P Coimbatore engineering",
    "Sakthivelpandian P Hayagreeva Vidhyalaya",
    "Sakthivelpandian P 9585992141",
    "Sakthivelpandian P imsakthidev@gmail.com",
    "Sakthivelpandian P GitHub profile",
    "Sakthivelpandian P Vercel app",
    "Sakthivelpandian P web app developer",
    "Sakthivelpandian P full stack engineer",
    "Sakthivelpandian P AI chatbot engineer",
    "Sakthivelpandian P prompt engineer",
    "Sakthivelpandian P Gemini API",
    "Sakthivelpandian P Vercel AI SDK",
    "Sakthivelpandian P Nextjs 16",
    "Sakthivelpandian P Turbopack",
    "Sakthivelpandian P Tailwind CSS",
    "Sakthivelpandian P TypeScript",
    "Sakthivelpandian P JavaScript",
    "Sakthivelpandian P MongoDB",
    "Sakthivelpandian P Expressjs",
    "Sakthivelpandian P REST API",
    "Sakthivelpandian P GIS mapping",
    "Sakthivelpandian P digital map editing",
    "Sakthivelpandian P operational mapping",
    "Sakthivelpandian P GPS data",
    "Sakthivelpandian P SSB seizure operation",
    "Sakthivelpandian P Commandant letter",
    "Sakthivelpandian P computer science teacher",
    "Sakthivelpandian P Python C++ SQL",
    "Sakthivelpandian P Class 11 12 teacher",
    "Sakthivelpandian P Tamilnadu College of Engineering",
    "Sakthivelpandian P BE CS 2017",
    "Sakthivelpandian P Available for Hire",
    "How to contact Sakthivelpandian P",
    "Sakthivelpandian P phone number 9585992141",
    "Sakthivelpandian P email address imsakthidev@gmail.com",
    "Sakthivelpandian P location Theni Tamilnadu",
    "Who is Sakthivelpandian P",
    "Sakthivelpandian P software developer profile",
    "Sakthivelpandian P official portfolio link",
    "Sakthivelpandian P web development services"
]

# Preserve order and ensure exact uniqueness
unique_keywords = []
seen = set()
for kw in raw_keywords:
    kw_clean = kw.strip()
    if kw_clean not in seen:
        seen.add(kw_clean)
        unique_keywords.append(kw_clean)

print(f"Total Unique Keywords: {len(unique_keywords)}")

target_file = "/Users/imsakthidev/Desktop/Projects/my-portfolio/src/app/layout.tsx"
with open(target_file, "r", encoding="utf-8") as f:
    content = f.read()

# Build replacement string for keywords array
formatted_keywords = "  keywords: [\n" + ",\n".join(f'    "{kw}"' for kw in unique_keywords) + "\n  ],"

# Replace keywords pattern in layout.tsx
new_content = re.sub(r'keywords:\s*\[.*?\]\s*,', formatted_keywords + ',', content, flags=re.DOTALL)

with open(target_file, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Successfully updated src/app/layout.tsx with 500 keywords!")
